/**
 * Development environment — replaces `environment.ts` for `ng serve` and
 * `ng build --configuration development` (see `fileReplacements` in angular.json).
 *
 * How this file was built: generated by `yarn ng g environments`, then given the same keys as
 * `environment.ts`.
 */
export const environment = {
  production: false,
  baseUrl: '',
  mockApi: true,
};
