/**
 * Router `TitleStrategy` that writes "<translated page title> · <application name>" into the
 * document title.
 *
 * How this file was built:
 *   1. `yarn ng g service core/title/page-title-strategy` generated an empty `@Service()` class
 *      and its spec.
 *   2. Made it extend `TitleStrategy` from `@angular/router` (itself a `@Service()` in v22 whose
 *      default implementation is `DefaultTitleStrategy`) and overrode `updateTitle()`, which the
 *      router calls after every navigation, to store the `title` of the deepest active route.
 *   3. Added `setAppName()`; `App` passes it the `title` signal generated by `ng new`.
 *   4. Added a `computed()` that composes the document title and an `effect()` that writes it
 *      whenever the page, the application name or the language changes.
 *   5. app.config.ts provides it as `{ provide: TitleStrategy, useExisting: PageTitleStrategy }`.
 *
 * Why: routes declare `title: 'menu.dashboard'` (an i18n key) and stay unaware of the product
 * name; the browser tab, history and bookmarks still say which page and which application they
 * belong to (WCAG 2.4.2 "Page Titled"). `TranslateService.instant()` reads ngx-translate's
 * signals, so switching the language retitles the current page without a navigation.
 */
import { computed, effect, inject, Service, signal } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { RouterStateSnapshot, TitleStrategy } from '@angular/router';
import { TranslateService } from '@ngx-translate/core';

/** Separates the page title from the application name. */
export const PAGE_TITLE_SEPARATOR = ' · ';

@Service()
export class PageTitleStrategy extends TitleStrategy {
  readonly #title = inject(Title);
  readonly #translate = inject(TranslateService);

  readonly #appName = signal('');
  /** The application name (set by `App`), e.g. for the branding of the layout. */
  readonly appName = this.#appName.asReadonly();
  /** `title` of the active route: an i18n key or plain text; `undefined` when it has none. */
  readonly #routeTitle = signal<string | undefined>(undefined);

  /** The full document title for the current page, application name and language. */
  readonly #documentTitle = computed(() => {
    const appName = this.#appName();
    const routeTitle = this.#routeTitle();
    const pageTitle = routeTitle ? String(this.#translate.instant(routeTitle)) : '';
    return [pageTitle, appName].filter(Boolean).join(PAGE_TITLE_SEPARATOR);
  });

  constructor() {
    super();
    effect(() => this.#write(this.#documentTitle()));
  }

  /** Sets the application name and shows it in the document title right away. */
  setAppName(name: string): void {
    this.#appName.set(name);
    this.#write(this.#documentTitle());
  }

  override updateTitle(snapshot: RouterStateSnapshot): void {
    this.#routeTitle.set(this.buildTitle(snapshot));
    this.#write(this.#documentTitle());
  }

  /** An empty title would replace the `<title>` of index.html with nothing; keep it instead. */
  #write(documentTitle: string): void {
    if (documentTitle) {
      this.#title.setTitle(documentTitle);
    }
  }
}
