/**
 * `<app-error-code>`: a large status code with a title, a message and a way back home.
 *
 * How this file was built:
 *   1. `yarn ng g component shared/error-code --inline-template --inline-style` generated the
 *      component and its spec.
 *   2. Inputs `code` (required), `heading` and `message` (text or translation keys); the code and
 *      heading form the page's `<h1>`, followed by a router link to the home page. (Not `title`:
 *      a static `title="…"` attribute would also show the key as a tooltip on the host.)
 *   3. ng-matero's "long shadow" of the code is generated by a Sass loop on the
 *      `--mat-sys-on-surface` color, so it stays visible in the dark theme.
 *
 * Why: ng-matero's pages passed English literals, its "Back to Home" button was untranslated and
 * the code was a plain `<div>`, so the page had no heading.
 */
import { Component, input } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { RouterLink } from '@angular/router';
import { TranslatePipe } from '@ngx-translate/core';

@Component({
  imports: [MatButtonModule, RouterLink, TranslatePipe],
  selector: 'app-error-code',
  styles: `
    @use 'sass:list';
    @use 'sass:math';

    // Shadows from 3% to 0.15% of the text color, 45° down to the right, 3.75rem long.
    @function long-shadow($length, $count) {
      $shadows: ();
      @for $i from 1 through $count {
        $offset: math.div($i * $length, $count) * math.sin(45deg);
        $alpha: 3% - math.div(2.85% * ($i - 1), $count - 1);
        $shadows: list.append(
          $shadows,
          $offset $offset 0 color-mix(in srgb, var(--mat-sys-on-surface) $alpha, transparent),
          comma
        );
      }
      @return $shadows;
    }

    :host {
      display: block;
      text-align: center;
    }

    h1 {
      margin: 0 0 1rem;
      font: var(--mat-sys-title-large);
    }

    .code {
      display: block;
      padding: 1.25rem 0;
      font-size: clamp(6rem, 25vw, 10rem);
      font-weight: 400;
      line-height: 1;
      text-shadow: long-shadow(3.75rem, 20);
    }

    p {
      margin: 0 0 1rem;
      font: var(--mat-sys-body-large);
    }
  `,
  template: `
    <h1>
      <span class="code">{{ code() }}</span>
      {{ heading() | translate }}
    </h1>
    @if (message()) {
      <p>{{ message() | translate }}</p>
    }
    <a matButton="elevated" routerLink="/">{{ 'error.back_home' | translate }}</a>
  `,
})
export class ErrorCode {
  readonly code = input.required<string>();
  readonly heading = input('');
  readonly message = input('');
}
